version: 2.1

jobs:

  build:
    docker:
      - image: cimg:17.1.0
    steps:
      - run: npm run lint

  test:
    docker:
      - image: cimg:17.1.0
    steps:
      - run: npm run test

  analyze:
    docker:
      - image: cimg:17.1.0
    steps:
      - run: npm audit

workflows:
  features:
    jobs:
      - build
      - test:
        requires:
          - build
      - analyze:
        requires:
          - test

